--Participantes--
SELECT SINIESTR.nsiniest "IDENTIFICADOR SINIESTRO",
TO_DATE((CASE WHEN SUBSTR(SINIESTR.fechasin ,1,1) = '1' THEN CONCAT(CONCAT(SUBSTR(SINIESTR.fechasin ,6,2),CONCAT('/',SUBSTR(SINIESTR.fechasin ,4,2))),CONCAT('/',CONCAT('20',SUBSTR(SINIESTR.fechasin ,2,2)))) 
ELSE CONCAT(CONCAT(SUBSTR(SINIESTR.fechasin ,6,2),CONCAT('/',SUBSTR(SINIESTR.fechasin ,4,2))),CONCAT('/',CONCAT('19',SUBSTR(SINIESTR.fechasin ,2,2)))) END),'DD/MM/YYYY') "FECHA SINIESTRO",
SINIESTR.nombcont "NOMBRE TITULAR POLIZA",
SINIESTR.nombtit "NOMBRE ASEGURADO POLIZA",
POL.nagente_1 "IDENTIFICADOR AGENTE",
OFI.num_oficina "IDENTIFICADOR OFICINA",
OFI.nom_oficina "NOMBRE OFICINA",
CASE WHEN RECLAM.rfcmed_1 IS NULL THEN 
CASE WHEN RECLAM.rfcmed_2 IS NULL THEN 
CASE WHEN RECLAM.rfcmed_3 IS NULL THEN 
CASE WHEN RECLAM.rfcmed_4 IS NULL THEN 
CASE WHEN RECLAM.rfcmed_5 IS NULL THEN 'NO DISPONIBLE'
ELSE RECLAM.rfcmed_5 END
ELSE RECLAM.rfcmed_4 END 
ELSE RECLAM.rfcmed_3 END 
ELSE RECLAM.rfcmed_2 END
ELSE RECLAM.rfcmed_1 END "MEDICO",
RECLAM.rfcinst "RFC INSTITUCION",
INST.nombinst "INSTITUCION",
RECLAM.idcapt "IDENTIFICADOR DICTAMINADOR"
--
FROM DWHRAW.ST_SINI_SINIESTR SINIESTR,
DWHRAW.S_SABE_POLIZA POL,
DWHRAW.S_CUA_TOFICINAADN OFI,
DWHRAW.ST_SINI_RECLAM RECLAM,
DWHRAW.S_SABE_INSTITUC INST
--
WHERE 1=1
--
AND POL.ramsubramo = SINIESTR.ramsubramo
AND POL.npoliza = SINIESTR.npoliza
AND OFI.cve_age = POL.nagente_1
AND RECLAM.nsiniest = SINIESTR.nsiniest
AND INST.rfcinst = RECLAM.rfcinst
--
AND POL.estatus_ind = 1
AND INST.estatus_ind = 1
